# Generated by Django 3.0.5 on 2020-05-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200515_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.IntegerField(default=0),
        ),
    ]
