# Generated by Django 3.0.5 on 2020-05-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
