# Generated by Django 3.0.5 on 2020-05-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200515_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_student',
            new_name='role',
        ),
    ]
