# Generated by Django 3.0.5 on 2020-05-19 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200517_0046'),
        ('users', '0005_auto_20200515_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fk_idclassroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.ClassRoom'),
        ),
    ]
