# Generated by Django 3.0.5 on 2020-05-17 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_trimester', models.FloatField(default=0, max_length=50)),
                ('second_trimester', models.FloatField(default=0, max_length=50)),
                ('third_trimester', models.FloatField(default=0, max_length=50)),
                ('final_exam', models.FloatField(default=0, max_length=50)),
                ('fk_idsubject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.Subjects')),
                ('fk_iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
