# Generated by Django 3.0.5 on 2020-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_exam',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='first_trimester',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='second_trimester',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='third_trimester',
            field=models.FloatField(default=0),
        ),
    ]
