# Generated by Django 3.0.5 on 2020-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200517_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='schedule',
            field=models.CharField(default='NO HORARIO', max_length=100),
        ),
    ]
